build:
  environment:
    pythonVersion: 3.11
  buildCommand: |
    set -e
    rm -rf /opt/render/project/src/.venv
    command -v python3.11
    python3.11 -m venv /opt/render/project/src/.venv
    /opt/render/project/src/.venv/bin/python -V
    /opt/render/project/src/.venv/bin/python -m pip install --upgrade pip setuptools wheel
    PIP_PREFER_BINARY=1 /opt/render/project/src/.venv/bin/pip install -r requirements.txt
startCommand: /opt/render/project/src/.venv/bin/gunicorn run:app --bind 0.0.0.0:$PORT
