build:
  environment:
    pythonVersion: 3.11
  buildCommand: |
    rm -rf .venv
    python3.11 -m venv .venv
    .venv/bin/python -m pip install --upgrade pip setuptools wheel
    PIP_ONLY_BINARY=:all: .venv/bin/pip install -r requirements.txt
startCommand: .venv/bin/gunicorn run:app
